name: Tests
on:
  push:
    branches:
      - main
      - staging
    paths-ignore:
      - '**/*.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.3.1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest
